-- CreateEnum
CREATE TYPE "Pantalla" AS ENUM ('PUNTO_DE_VENTA', 'FACTURACION', 'COMPROBANTES_EMITIDOS', 'CLIENTES', 'CUENTAS_CORRIENTES', 'PROVEEDORES', 'COMPROBANTES_COMPRA', 'PRODUCTOS', 'STOCK', 'CONTABILIDAD');

-- AlterTable
ALTER TABLE "usuarios" ADD COLUMN     "pantallasPermitidas" "Pantalla"[] DEFAULT ARRAY[]::"Pantalla"[];
